-- local dap = require("dap")
-- local dapui = require("dapui")
--
-- require("dap-python").setup("python3")
-- require('dap-python').test_runner = 'pytest'
-- require("dap-go").setup()
-- require("nvim-dap-virtual-text").setup()
-- dapui.setup()
-- dap.listeners.before.attach.dapui_config = function()
--   dapui.open()
-- end
-- dap.listeners.before.launch.dapui_config = function()
--   dapui.open()
-- end
-- dap.listeners.before.event_exited.dapui_config = function()
--   dapui.close()
-- end
-- dap.listeners.before.event_terminated.dapui_config = function()
--   dapui.close()
-- end
