require("alternate")
require("globals")
require("lsp.init")
-- require("lsp-config")
require("plugins.formatter")
require("plugins.misc")
require("plugins.cmp")
require("plugins.nvim-dap")
require("plugins.nvim-tree")
